//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVC2
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO
    {
        public int empleado_id { get; set; }
        public string empleado_paterno { get; set; }
        public string empleado_materno { get; set; }
        public string empleado_nombres { get; set; }
        public int empleado_edad { get; set; }
    }
}
