//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Semana11
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumnos
    {
        public int DNI { get; set; }
        public string APA { get; set; }
        public string AMA { get; set; }
        public string NOM { get; set; }
        public string CODC { get; set; }
        public string CODT { get; set; }
    
        public virtual Carreras Carreras { get; set; }
        public virtual Turno Turno { get; set; }
    }
}
